using Restaurant.Domain.Entities;

namespace Restaurant.DataAccess.Seed;

public static class IngredientSeedData
{
    public static List<Ingredient> GetIngredients() => new()
    {
        // ── Meat & Seafood ───────────────────────────────────────────────────
        new Ingredient { Name = "eggs",          Category = "meat",      Unit = "pcs" },
        new Ingredient { Name = "bacon",         Category = "meat",      Unit = "g"   },
        new Ingredient { Name = "guanciale",     Category = "meat",      Unit = "g"   },
        new Ingredient { Name = "anchovies",     Category = "meat",      Unit = "g"   },
        new Ingredient { Name = "salmon",        Category = "meat",      Unit = "g"   },
        new Ingredient { Name = "lobster",       Category = "meat",      Unit = "g"   },
        new Ingredient { Name = "squid",         Category = "meat",      Unit = "g"   },
        new Ingredient { Name = "beef",          Category = "meat",      Unit = "g"   },
        new Ingredient { Name = "chicken",       Category = "meat",      Unit = "g"   },
        new Ingredient { Name = "lamb",          Category = "meat",      Unit = "g"   },
        new Ingredient { Name = "duck",          Category = "meat",      Unit = "g"   },
        new Ingredient { Name = "mussels",       Category = "meat",      Unit = "g"   },
        new Ingredient { Name = "shrimp",        Category = "meat",      Unit = "g"   },
        new Ingredient { Name = "chorizo",       Category = "meat",      Unit = "g"   },
        new Ingredient { Name = "sausages",      Category = "meat",      Unit = "pcs" },
        new Ingredient { Name = "plant protein", Category = "other",     Unit = "g"   },
        new Ingredient { Name = "jackfruit",     Category = "other",     Unit = "g"   },

        // ── Dairy ────────────────────────────────────────────────────────────
        new Ingredient { Name = "butter",        Category = "dairy",     Unit = "g"   },
        new Ingredient { Name = "milk",          Category = "dairy",     Unit = "ml"  },
        new Ingredient { Name = "almond milk",   Category = "dairy",     Unit = "ml"  },
        new Ingredient { Name = "feta",          Category = "dairy",     Unit = "g"   },
        new Ingredient { Name = "parmesan",      Category = "dairy",     Unit = "g"   },
        new Ingredient { Name = "pecorino",      Category = "dairy",     Unit = "g"   },
        new Ingredient { Name = "mozzarella",    Category = "dairy",     Unit = "g"   },
        new Ingredient { Name = "cream cheese",  Category = "dairy",     Unit = "g"   },
        new Ingredient { Name = "mascarpone",    Category = "dairy",     Unit = "g"   },
        new Ingredient { Name = "cream",         Category = "dairy",     Unit = "ml"  },
        new Ingredient { Name = "egg yolks",     Category = "dairy",     Unit = "pcs" },
        new Ingredient { Name = "vanilla ice cream", Category = "dairy", Unit = "g"   },

        // ── Vegetables ───────────────────────────────────────────────────────
        new Ingredient { Name = "avocado",       Category = "vegetables", Unit = "pcs" },
        new Ingredient { Name = "tomatoes",      Category = "vegetables", Unit = "g"   },
        new Ingredient { Name = "garlic",        Category = "vegetables", Unit = "pcs" },
        new Ingredient { Name = "mushrooms",     Category = "vegetables", Unit = "g"   },
        new Ingredient { Name = "asparagus",     Category = "vegetables", Unit = "g"   },
        new Ingredient { Name = "sweet potato",  Category = "vegetables", Unit = "g"   },
        new Ingredient { Name = "zucchini",      Category = "vegetables", Unit = "g"   },
        new Ingredient { Name = "lettuce",       Category = "vegetables", Unit = "g"   },
        new Ingredient { Name = "arugula",       Category = "vegetables", Unit = "g"   },
        new Ingredient { Name = "basil",         Category = "vegetables", Unit = "g"   },
        new Ingredient { Name = "onions",        Category = "vegetables", Unit = "pcs" },
        new Ingredient { Name = "berries",       Category = "vegetables", Unit = "g"   },
        new Ingredient { Name = "mixed berries", Category = "vegetables", Unit = "g"   },
        new Ingredient { Name = "banana",        Category = "vegetables", Unit = "pcs" },
        new Ingredient { Name = "cherries",      Category = "vegetables", Unit = "g"   },
        new Ingredient { Name = "passion fruit", Category = "vegetables", Unit = "pcs" },
        new Ingredient { Name = "oranges",       Category = "vegetables", Unit = "pcs" },
        new Ingredient { Name = "lemon",         Category = "vegetables", Unit = "pcs" },
        new Ingredient { Name = "lime",          Category = "vegetables", Unit = "pcs" },
        new Ingredient { Name = "mint",          Category = "vegetables", Unit = "g"   },
        new Ingredient { Name = "dill",          Category = "vegetables", Unit = "g"   },
        new Ingredient { Name = "herbs",         Category = "vegetables", Unit = "g"   },
        new Ingredient { Name = "carrots",       Category = "vegetables", Unit = "g"   },
        new Ingredient { Name = "parsnips",      Category = "vegetables", Unit = "g"   },
        new Ingredient { Name = "vegetables",    Category = "vegetables", Unit = "g"   },
        new Ingredient { Name = "potatoes",      Category = "vegetables", Unit = "g"   },
        new Ingredient { Name = "strawberries",  Category = "vegetables", Unit = "g"   },

        // ── Dry Goods ────────────────────────────────────────────────────────
        new Ingredient { Name = "english muffin",  Category = "dry goods", Unit = "pcs"   },
        new Ingredient { Name = "bread",           Category = "dry goods", Unit = "g"     },
        new Ingredient { Name = "pita",            Category = "dry goods", Unit = "pcs"   },
        new Ingredient { Name = "pasta",           Category = "dry goods", Unit = "g"     },
        new Ingredient { Name = "flour",           Category = "dry goods", Unit = "g"     },
        new Ingredient { Name = "almond flour",    Category = "dry goods", Unit = "g"     },
        new Ingredient { Name = "arborio rice",    Category = "dry goods", Unit = "g"     },
        new Ingredient { Name = "rice",            Category = "dry goods", Unit = "g"     },
        new Ingredient { Name = "corn tortillas",  Category = "dry goods", Unit = "pcs"   },
        new Ingredient { Name = "ladyfingers",     Category = "dry goods", Unit = "pcs"   },
        new Ingredient { Name = "graham crackers", Category = "dry goods", Unit = "g"     },
        new Ingredient { Name = "granola",         Category = "dry goods", Unit = "g"     },
        new Ingredient { Name = "brioche",         Category = "dry goods", Unit = "g"     },
        new Ingredient { Name = "croutons",        Category = "dry goods", Unit = "g"     },
        new Ingredient { Name = "toast",           Category = "dry goods", Unit = "pcs"   },
        new Ingredient { Name = "chickpeas",       Category = "dry goods", Unit = "g"     },
        new Ingredient { Name = "baked beans",     Category = "dry goods", Unit = "g"     },
        new Ingredient { Name = "walnuts",         Category = "dry goods", Unit = "g"     },
        new Ingredient { Name = "pistachios",      Category = "dry goods", Unit = "g"     },
        new Ingredient { Name = "coconut",         Category = "dry goods", Unit = "g"     },
        new Ingredient { Name = "quinoa",          Category = "dry goods", Unit = "g"     },
        new Ingredient { Name = "sugar",           Category = "dry goods", Unit = "g"     },
        new Ingredient { Name = "gelatin",         Category = "dry goods", Unit = "g"     },
        new Ingredient { Name = "cocoa",           Category = "dry goods", Unit = "g"     },
        new Ingredient { Name = "cocoa powder",    Category = "dry goods", Unit = "g"     },
        new Ingredient { Name = "chocolate",       Category = "dry goods", Unit = "g"     },

        // ── Spices & Condiments ───────────────────────────────────────────────
        new Ingredient { Name = "black pepper",    Category = "spices", Unit = "g"  },
        new Ingredient { Name = "cinnamon",        Category = "spices", Unit = "g"  },
        new Ingredient { Name = "saffron",         Category = "spices", Unit = "g"  },
        new Ingredient { Name = "capers",          Category = "spices", Unit = "g"  },
        new Ingredient { Name = "truffle",         Category = "spices", Unit = "g"  },
        new Ingredient { Name = "vanilla",         Category = "spices", Unit = "g"  },
        new Ingredient { Name = "vanilla bean",    Category = "spices", Unit = "pcs"},
        new Ingredient { Name = "maple syrup",     Category = "spices", Unit = "ml" },
        new Ingredient { Name = "olive oil",       Category = "spices", Unit = "ml" },
        new Ingredient { Name = "tahini",          Category = "spices", Unit = "g"  },
        new Ingredient { Name = "vegan mayo",      Category = "spices", Unit = "g"  },
        new Ingredient { Name = "mayonnaise",      Category = "spices", Unit = "g"  },
        new Ingredient { Name = "tomato sauce",    Category = "spices", Unit = "ml" },
        new Ingredient { Name = "balsamic vinegar",Category = "spices", Unit = "ml" },

        // ── Drinks ───────────────────────────────────────────────────────────
        new Ingredient { Name = "white wine",      Category = "drinks", Unit = "ml"    },
        new Ingredient { Name = "red wine",        Category = "drinks", Unit = "ml"    },
        new Ingredient { Name = "vegetable stock", Category = "drinks", Unit = "ml"    },
        new Ingredient { Name = "soda water",      Category = "drinks", Unit = "ml"    },
        new Ingredient { Name = "mineral water",   Category = "drinks", Unit = "ml"    },
        new Ingredient { Name = "water",           Category = "drinks", Unit = "ml"    },
        new Ingredient { Name = "grapes",          Category = "drinks", Unit = "g"     },
        new Ingredient { Name = "coffee beans",    Category = "drinks", Unit = "g"     },
        new Ingredient { Name = "coffee",          Category = "drinks", Unit = "g"     },
        new Ingredient { Name = "matcha powder",   Category = "drinks", Unit = "g"     },
        new Ingredient { Name = "malt",            Category = "drinks", Unit = "g"     },
        new Ingredient { Name = "hops",            Category = "drinks", Unit = "g"     },
        new Ingredient { Name = "yeast",           Category = "drinks", Unit = "g"     },
        new Ingredient { Name = "ice",             Category = "drinks", Unit = "g"     },
    };
}